import raw from "./film.json";

export type ShotKind = "F" | "G" | "C";

export type ShotData = {
  readonly id: string;
  readonly chapter: number;
  readonly scene: string;
  readonly kind: ShotKind;
  readonly ref: string;
  readonly from: number;
  readonly frames: number;
  readonly tail: number;
  readonly srcStart: number;
  readonly tag: string | null;
  readonly ai: boolean;
};

export type Word = { readonly t: number; readonly w: string };

export type Cue = { readonly from: number; readonly to: number; readonly lines: readonly string[] };

export type ChapterMeta = { readonly num: number; readonly name: string; readonly question: string };

export type FilmData = {
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly durationInFrames: number;
  readonly transitionFrames: number;
  readonly chapters: readonly ChapterMeta[];
  readonly shots: readonly ShotData[];
  readonly words: readonly Word[];
  readonly subtitles: readonly Cue[];
};

// Generated by scripts/v13_film.py export (narration timeline + shot plan).
export const film = raw as FilmData;
